### ISSUE TITLE
SLAB - Print below logs on same and one line

### ISSUE THREAD

**Issue by sameerpanicker** [mspnp/semantic-logging#75] opened 2016-04-15 04:22 UTC
What setting I need to change for printing below log on same line?

ProviderId : 46875d78-3924-5303-f49e-65b8bc0dc289
EventId : 11
Keywords : 1024
Level : Error
Message : Unexpected
Opcode : Info
Task : 1
Version : 1
Payload : [sessionID : e3491b01-40de-4dbf-8287-2bab1c81102e] [type : OperationCanceledException] [data : ] [innerException : ] [message : The operation was canceled.] [source : mscorlib] [stackTrace : atSystem.Threading.CancellationToken.ThrowOperationCanceledException()atSystem.Threading.CancellationToken.ThrowIfCancellationRequested()atSystem.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()---Endofstacktracefrompreviouslocationwhereexceptionwasthrown---atSystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()atSystem.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tasktask)atSystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Tasktask)atSystem.Runtime.CompilerServices.TaskAwaiter`1.GetResult()atSystem.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()---Endofstacktracefrompreviouslocationwhereexceptionwasthrown---atSystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()atSystem.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tasktask)atSystem.Runtime.Com

**Comment by arambarri** [comment] 2016-04-15 15:53
Hi @sameerpanicker 

I don’t know which sink you are using, but I'm sure you are using **EventTextFormatter** in order to write the log.

This Formatter creates one line log entry or multiple lines log entry based on the Event's Level. 
By default, the limit is **Error**. So, all the events with level less than **Error** wouldn't have the event detailed information.

For example: 
```
<rollingFlatFileSink name="RollingFlatFileSink" fileName="RollingFlatFile.log"                        timeStampPattern="yyyy" rollFileExistsBehavior="Overwrite" rollInterval="Day">
      <sources>
		 <eventSource name="Samples-EventSourceDemos-Minimal" level="LogAlways"/>
      </sources>
</rollingFlatFileSink>
   ```
   The output generated for an Information Event and an Error Event is the following:
   ```
EventId : 1, Level : Informational, Message : 200 -> Charlesこんにち, Payload : [baseAddress : 200] [imageName : Charlesこんにち] , EventName : LoadAdminInfo, Timestamp : 2016-04-15T14:22:30.8761043Z, ProcessId : 19240, ThreadId : 12980

ProviderId : bd0203f6-00b4-562f-d365-ee7cd5060d1d
EventId : 3
Keywords : None
Level : Error
Message : 
Opcode : Info
Task : 65531
Version : 0
Payload : [msg : I'm testing] 
EventName : logErrorInfo
Timestamp : 2016-04-15T14:22:30.8765251Z
ProcessId : 19240
ThreadId : 12980
   ```
It is possible to change the default to **Critical** (for example), then the Error messages (like your messages) will be in a line.
  
   ```
  <rollingFlatFileSink name="RollingFlatFileSink" fileName="RollingFlatFile.log"                   timeStampPattern="yyyy" rollFileExistsBehavior="Overwrite" rollInterval="Day">
      <sources>
		 <eventSource name="Samples-EventSourceDemos-Minimal" level="LogAlways"/>
      </sources>
	   <eventTextFormatter verbosityThreshold="Critical" />
   </rollingFlatFileSink>
    
EventId : 1, Level : Informational, Message : 200 -> Charlesこんにち, Payload : [baseAddress : 200] [imageName : Charlesこんにち] , EventName : LoadAdminInfo, Timestamp : 2016-04-15T15:23:23.7927630Z, ProcessId : 13920, ThreadId : 1636

EventId : 3, Level : Error, Message : , Payload : [msg : I'm testing] , EventName : logErrorInfo, Timestamp : 2016-04-15T15:23:23.7933134Z, ProcessId : 13920, ThreadId : 1636
 ```
If it is not enough for you, you will be able to create your [own formatter](https://msdn.microsoft.com/en-us/library/dn775004(v=pandp.20).aspx). 

Hope this help.

**Comment by sameerpanicker** [comment] 2016-04-15 19:20
I am using -

<rollingFlatFileSink name="MySecurityEventSource"
                         fileName="C:\ServiceLogs\\SecurityEventSource.txt"
                         rollSizeKB="3000"
                         rollFileExistsBehavior="Increment"
                         rollInterval="Midnight"
                         timeStampPattern="yyyy-MMM-d">
      <sources>
        <eventSource name="MyLoggingApp.EventSources.SecurityEventSource"
                     level="LogAlways" />
      </sources>
    </rollingFlatFileSink>

I have a custom class that inherits from EventSource.

[Event(
            1,
            Keywords = Keywords.ArgumentNull,
            Task = Tasks.Response,
            Level = EventLevel.Error,
            Message = "ArgumentNull",
            Version = 1)]
        public void ArgumentNull(Guid sessionID, string message, string paramName, string source, string stackTrace)
        {
            if (this.IsEnabled(EventLevel.Error, Keywords.ArgumentNull))
            {
                this.WriteEvent(1, sessionID, message, paramName, source, stackTrace.Replace(Environment.NewLine, string.Empty));
            }
        }

I tried changing the verbosity level but no luck.

**Comment by sameerpanicker** [comment] 2016-04-28 15:49
The whole reason of my query above was to read my logs using ELK stack. Yesterday, I came to know about the ElasticSearch sink, tried that and it worked fine. Now, its sending the data to ES directly. 
Can anyone tell me if there is any sink for logstash? So that I can edit the fields(add, replace or remove) as per my requirement. i.e. I want the event data to be sent to logstash and after editing it send it to ES.

**Comment by arambarri** [comment] 2016-04-28 16:01
Hi @sameerpanicker,

There is not a sink for logstash out-of-the-box. However, you can create [your own sink](https://msdn.microsoft.com/en-us/library/dn775003(v=pandp.20).aspx)

**Comment by sameerpanicker** [comment] 2016-04-28 16:35
Thanks for the quick reply arambarri. I will have a look into this.
There is one more thing regarding the customEventFormatter. I want to create a custom format hence, was trying to extend the EventTextFormatter using this link "http://www.shujaat.net/2013/09/entlib6-slab-custom-ieventtextformatter.html"

But was facing issue while starting Sem. Logg EXE.
![issues](https://cloud.githubusercontent.com/assets/12462947/14893486/45987960-0d35-11e6-81a9-67853c8a8e1f.png)

Could you please help me on this ?

**Comment by arambarri** [comment] 2016-04-28 17:13
I believe the issue is because of the custom library was compiled using a library version and it is using other in order to execute.

Please, in your Visual Studio solution, change the reference to Microsoft.Practices.EnterpriseLibrary.SemanticLogging.dll, and put the library which is on the directory where you are running. Recompile, deploy, and re-execute.

The [pull request 2](https://github.com/mspnp/semantic-logging/pull/2), could help you to get detailed information about the error

Please, let me know if it works.

**Comment by sameerpanicker** [comment] 2016-04-28 17:33
Got some of the errors removed. But still it didnt work. 
![issues](https://cloud.githubusercontent.com/assets/12462947/14895278/76521220-0d3d-11e6-97d1-e386eab714c9.png)

**Comment by arambarri** [comment] 2016-04-28 18:08
I've downloaded the Muhammad's Solution, I've changed the references on both projects and it is working properly.

I'm not able to figure out what is wrong on your environment. Please, also try changing the reference to Newtonsoft.Json.dll library. It is needed to compile the custom library using the same libraries which will be used to execute (Inside SLAB's installation folder).

**Comment by sameerpanicker** [comment] 2016-04-28 18:10
I will also give a try with Muh. solution. Will let u know the outcome.

**Comment by sameerpanicker** [comment] 2016-04-28 19:12
I was also able to run Muh. solution following the below steps.
- Using the reference of SemanticLogging and Json.dll from the EXE location.
- Building the solution
- Placing the dll in the EXE folder.

I followed the same step for my project. Still facing the same problem. :(

What can I try next ?

**Comment by arambarri** [comment] 2016-04-29 13:30
It might be a library which is referenced by your project at compile time, but it is not available at run time (because it is missing, or the versions differ).

You should check carefully your environment and you have to be sure to copy all the needed libraries to the execution folder.

If the problem persist, you can download the PR 2 and compile the semantic logging library. That new version, which is ready to merge,  will add detailed information about that error. If it is still not enough,  you will be able to debug.

The  Muhammad's Solution is working, you can also use it as starting point and refactor it little by little to achieve your goal.

Given that the original question is already answered, I will proceed to close this issue. However, feel free to raise a new issue if you find a bug, or ask any questions in our [Semantic Logging Gitter](https://gitter.im/mspnp/semantic-logging).

**Closed** 2016-04-29 13:32 UTC
